# Generated by Django 3.0.5 on 2021-09-10 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210910_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 7, 8, 36, 269062, tzinfo=utc)),
        ),
    ]
